package unbound

import (
	"fmt"
	"strings"

	"github.com/barry/AzureDNSForwarder/internal/config"
	"github.com/barry/AzureDNSForwarder/internal/unbound/proxy"
)

// ProxyAddr returns the loopback address that the least-latency proxy binds
// to. The proxy package owns the default; this helper exposes it for config
// generation.
func ProxyAddr() string { return proxy.DefaultListen }

// Generate produces an unbound.conf that reflects the supplied config.
// The output is deterministic and self-contained: dnsforwarderd supervises
// the unbound process, so this file does not need to include any system
// defaults or include files.
func Generate(f *config.File) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by AzureDNSForwarder - do not edit by hand.\n")
	b.WriteString("server:\n")
	b.WriteString("\tverbosity: 1\n")
	b.WriteString("\tinterface-automatic: no\n")
	host, port := splitHostPort(f.Settings.DNSListen, 53)
	b.WriteString(fmt.Sprintf("\tinterface: %s\n", host))
	b.WriteString(fmt.Sprintf("\tport: %d\n", port))
	b.WriteString("\tdo-ip4: yes\n")
	b.WriteString("\tdo-ip6: yes\n")
	b.WriteString("\tdo-udp: yes\n")
	b.WriteString("\tdo-tcp: yes\n")
	b.WriteString("\tcache-min-ttl: 60\n")
	b.WriteString("\tcache-max-ttl: 86400\n")
	b.WriteString(fmt.Sprintf("\tmsg-cache-size: %d\n", f.Settings.CacheSize))
	b.WriteString(fmt.Sprintf("\trrset-cache-size: %d\n", f.Settings.CacheSize))
	if f.Settings.DNSSEC {
		b.WriteString("\tmodule-config: \"validator iterator\"\n")
		b.WriteString("\ttrust-anchor-signaling: yes\n")
	} else {
		b.WriteString("\tmodule-config: \"iterator\"\n")
	}
	if f.Settings.LogQueries {
		b.WriteString("\tverbosity: 2\n")
	}
	b.WriteString("\tdirectory: \"/etc/unbound\"\n")
	b.WriteString("\tusername: \"dnsfwd\"\n")
	b.WriteString("\tuse-syslog: no\n")
	b.WriteString("\tlogfile: \"/dev/stdout\"\n")
	b.WriteString("\tnum-threads: 1\n")
	// Without explicit access-control, unbound defaults to refusing queries
	// from any address outside 127.0.0.0/8. Allow all queries so the container
	// works correctly when Docker forwards traffic from the bridge gateway.
	b.WriteString("\taccess-control: 0.0.0.0/0 allow\n")
	b.WriteString("\taccess-control: ::/0 allow\n")
	b.WriteString("\tunwanted-reply-threshold: 0\n")
	b.WriteString("\tprivate-address: 168.63.129.16\n")
	b.WriteString("\tprivate-address: 169.254.169.254\n")
	// Unbound defaults do-not-query-localhost: yes, which prevents forwarding
	// least-latency zones to the internal loopback proxy at 127.0.0.1:15353.
	// Disable that restriction so the local latency proxy can be used.
	b.WriteString("\tdo-not-query-localhost: no\n")
	b.WriteString("\n")

	if len(f.StaticRecords) > 0 {
		// local-data must precede forward-zone in unbound's config parser
		// (verified against unbound 1.20.0; the inverse order triggers a
		// spurious syntax error on the first local-data line). The
		// remote-control: block also cannot appear before local-data.
		for _, r := range f.StaticRecords {
			if r.Deleted {
				continue
			}
			name := ensureFQDN(r.Name)
			val := r.Value
			if r.Type == "CNAME" && !strings.HasSuffix(val, ".") {
				val = ensureFQDN(val)
			}
			switch strings.ToUpper(r.Type) {
			case "A":
				fmt.Fprintf(&b, "local-data: \"%s %d IN A %s\"\n", name, r.TTL, val)
			case "AAAA":
				fmt.Fprintf(&b, "local-data: \"%s %d IN AAAA %s\"\n", name, r.TTL, val)
			case "CNAME":
				fmt.Fprintf(&b, "local-data: \"%s %d IN CNAME %s\"\n", name, r.TTL, val)
			}
		}
		b.WriteString("\n")
	}

	enabled := []config.UpstreamDefault{}
	for _, u := range f.UpstreamDefaults {
		if u.Deleted || !u.Enabled {
			continue
		}
		enabled = append(enabled, u)
	}
	if len(enabled) > 0 {
		b.WriteString("forward-zone:\n")
		b.WriteString("\tname: \".\"\n")
		for _, u := range enabled {
			b.WriteString(fmt.Sprintf("\tforward-addr: %s\n", u.Address))
			if u.Port != 53 {
				b.WriteString(fmt.Sprintf("\tforward-port: %d\n", u.Port))
			}
		}
		b.WriteString("\tforward-tls-upstream: no\n")
		b.WriteString("\n")
	}

	for _, z := range f.ForwardZones {
		if z.Deleted {
			continue
		}
		b.WriteString("forward-zone:\n")
		name := strings.TrimPrefix(z.Name, "*.")
		b.WriteString(fmt.Sprintf("\tname: \"%s\"\n", name))
		if z.LeastLatency {
			// Exact-match least-latency zones are served by the internal
			// loopback proxy. The proxy runs the upstream query, pings
			// every returned record, and returns the lowest-latency answers.
			// Unbound uses 'forward-addr: host@port' syntax; the separate
			// 'forward-port' keyword is for the zone-wide default and cannot
			// appear after individual forward-addr lines.
			host, port := splitHostPort(proxy.DefaultListen, proxy.DefaultListenPort)
			if port != 53 {
				host = fmt.Sprintf("%s@%d", host, port)
			}
			b.WriteString(fmt.Sprintf("\tforward-addr: %s\n", host))
		} else {
			for _, u := range z.Upstreams {
				host, port := splitHostPort(u, 53)
				b.WriteString(fmt.Sprintf("\tforward-addr: %s\n", host))
				if port != 53 {
					b.WriteString(fmt.Sprintf("\tforward-port: %d\n", port))
				}
			}
		}
		b.WriteString("\tforward-tls-upstream: no\n")
		b.WriteString("\n")
	}

	b.WriteString("remote-control:\n")
	b.WriteString("\tcontrol-enable: no\n")
	return b.String(), nil
}

func ensureFQDN(name string) string {
	if strings.HasSuffix(name, ".") {
		return name
	}
	return name + "."
}

func splitHostPort(s string, def int) (string, int) {
	s = strings.TrimSpace(s)
	if !strings.Contains(s, ":") {
		return s, def
	}
	// Handle IPv6 "[::1]:53" form.
	if strings.HasPrefix(s, "[") {
		end := strings.Index(s, "]")
		if end < 0 {
			return s, def
		}
		host := s[:end+1]
		rest := s[end+1:]
		if strings.HasPrefix(rest, ":") {
			rest = rest[1:]
		}
		var p int
		fmt.Sscanf(rest, "%d", &p)
		if p == 0 {
			p = def
		}
		return host, p
	}
	// Plain "host:port".
	idx := strings.LastIndex(s, ":")
	host := s[:idx]
	rest := s[idx+1:]
	var p int
	fmt.Sscanf(rest, "%d", &p)
	if p == 0 {
		p = def
	}
	return host, p
}
